apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - https://github.com/openvinotoolkit/model_server/extras/ovms-operator/config/default?ref=v2021.4.1

images:
- name: controller
  newName: quay.io/openvino/ovms-operator
  newTag: 0.1.0
